### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by Ezharjan** [IntelLabs/csg#9]
**What is your Python Version while running the installation process?**

When I run `pip install -r requirements.txt` under `conda` environment of **Python3.9 on my Linux Ubuntu 20.04 LTS**, it outputs the message as follows:

```bash
...
Collecting tensorflow-gpu==2.12.0
  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Traceback (most recent call last):
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/_vendor/packaging/requirements.py", line 35, in __init__
          parsed = _parse_requirement(requirement_string)
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/_vendor/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/_vendor/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
          raise ParserSyntaxError(
      setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vyq5no4p/tensorflow-gpu_413d9a4060b747d8bc9ab94ec76b357c/setup.py", line 40, in <module>
          setuptools.setup()
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/__init__.py", line 73, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/dist.py", line 655, in parse_config_files
          self._finalize_requires()
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/dist.py", line 390, in _finalize_requires
          self._normalize_requires()
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/dist.py", line 405, in _normalize_requires
          self.install_requires = list(map(str, _reqs.parse(install_requires)))
        File "/home/alex/anaconda3/envs/csg/lib/python3.9/site-packages/setuptools/_vendor/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
I have changed to different versions of Python (3.6, 3.7, 3.8, 3.9, 3.12) to retry, but I gain almost the same error on installing the prerequisites.
Do you have some suggestions on the environment?

**Comment by Ezharjan** [comment]
Besides, `tensorflow-gpu==2.12.0` seem to cause some weird issues before changing it into `tensorflow==2.12.0`. 
Here is my updated version of `requirements.txt`:
```
commonroad-io==2022.1
cython-bbox==0.1.3
easydict==1.10
h5py==3.7.0
ipython==8.10.0
keras==2.11.0
lap==0.4.0
numba==0.56.4
opencv-python==4.6.0.66
Pillow==9.5.0
pycocotools==2.0.6
pykalman==0.9.5
python-magic==0.4.27
PyYAML==6.0
scikit-image==0.19.3
scikit-learn==1.2.0
scipy==1.10.0
tensorflow==2.12.0
torch==1.13.1
vtk==9.2.2
```

**Comment by olek-osikowicz** [comment]
I also changed  `tensorflow-gpu==2.12.0` to `tensorflow==2.12.0`

**Comment by olek-osikowicz** [comment]
@Ezharjan I've managed to run the pipeline with the following conda environment: 
https://pastebin.com/3uMErfKT

Also look at the issue #11 with PIL package bump.

**Comment by Ezharjan** [comment]
> @Ezharjan I've managed to run the pipeline with the following conda environment: https://pastebin.com/3uMErfKT
> 
> Also look at the issue #11 with PIL package bump.

Thanks! This works for me~
